name: Code style check

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string
      cwd:
        default: "."
        type: string

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Get Composer Cache Directory
        run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-interaction
        working-directory: ${{ inputs.cwd == '.' && './' || format('./{0}', inputs.cwd) }}

      - name: Execute code style check
        run: vendor/bin/pint --test
        working-directory: ${{ inputs.cwd == '.' && './' || format('./{0}', inputs.cwd) }}
