name: Static analysis

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none

      - name: Get Composer Cache Directory
        run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }'
        run: composer install --no-interaction

      - name: Execute type checking
        run: vendor/bin/phpstan analyse
