name: Tests

on:
  workflow_call:
    inputs:
      php:
        description: 'Specify the php version (https://github.com/shivammathur/setup-php#tada-php-support)'
        type: string
        required: true
      passport:
        description: 'Generate private and public keys for Laravel Passport'
        type: boolean
        required: true
      subdirectory:
        description: 'Specify the subdirectory of the project. Useful for monorepos. (e.g., "backend")'
        type: string
        required: false
        default: ''

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format directory path
        id: format-directory
        run: |
          formattedDir="${{ format('{0}/{1}', github.workspace, inputs.subdirectory) }}"
          formattedDir="${formattedDir%/}" # Remove trailing slash if present
          echo "dir=${formattedDir}" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles(format('{0}/{1}', steps.format-directory.outputs.dir, 'composer.lock')) }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-interaction
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Setup Passport
        if: ${{ inputs.passport }}
        run: php artisan passport:keys --force
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Execute tests
        run: php artisan test --parallel --env=testing
        working-directory: ${{ steps.format-directory.outputs.dir }}
