name: Deployment

on:
  workflow_call:
    inputs:
      php:
        description: 'Specify the php version. [Docs](https://github.com/shivammathur/setup-php#tada-php-support)'
        type: string
        required: true
      subdirectory:
        description: 'Specify the subdirectory of the project. Useful for monorepos. (e.g., "backend")'
        type: string
        required: false
        default: ''
      environment:
        description: 'Specify the environment to deploy to (e.g., "production" | "staging")'
        type: string
        required: true
      version:
        description: 'Specify the version to deploy (e.g., "v1.0.0")'
        type: string
        required: true

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format directory path
        id: format-directory
        run: |
          formattedDir="${{ format('{0}/{1}', github.workspace, inputs.subdirectory) }}"
          formattedDir="${formattedDir%/}" # Remove trailing slash if present
          echo "dir=${formattedDir}" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles(format('{0}/{1}', steps.format-directory.outputs.dir, 'composer.lock')) }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-interaction
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Download dotenv script
        run: |
          curl https://raw.githubusercontent.com/bashup/dotenv/master/dotenv --output dotenv
          chmod +x dotenv
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Download environment
        run: vapor env:pull ${{ inputs.environment }}
        working-directory: ${{ steps.format-directory.outputs.dir }}
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Set APP_VERSION
        run: ./dotenv -f ${{ format('.env.{0}', inputs.environment) }} set APP_VERSION="${{ inputs.version }}"
        working-directory: ${{ steps.format-directory.outputs.dir }}

      - name: Upload environment
        run: vapor env:push ${{ inputs.environment }} --keep
        working-directory: ${{ steps.format-directory.outputs.dir }}
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
