name: Deployment

on:
  workflow_call:
    inputs:
      php:
        description: 'Specify the php version. [Docs](https://github.com/shivammathur/setup-php#tada-php-support)'
        type: string
        required: true
      environment:
        description: 'Specify the environment to deploy to (e.g., "production" | "staging")'
        type: string
        required: true
      version:
        description: 'Specify the version to deploy (e.g., "v1.0.0")'
        type: string
        required: true

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-interaction

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli

      - name: Download dotenv script
        run: |
          curl https://raw.githubusercontent.com/bashup/dotenv/master/dotenv --output dotenv
          chmod +x dotenv

      - name: Download environment
        run: vapor env:pull ${{ inputs.environment }}
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Set APP_VERSION
        run: ./dotenv -f ${{ format('.env.{0}', inputs.environment) }} set APP_VERSION="${{ inputs.version }}"

      - name: Upload environment
        run: vapor env:push ${{ inputs.environment }} --keep
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
